site.home.title: 'Веб Приложения для игр и обучения: KidsChess, Cribbage'
site.home.h1: 'Игровые Веб-Приложения'
site.home.h2: 'Играй и изучай в удовольствие'
site.home.section1.main: 'KidsChess: Шахматные игры для детей'
site.home.section1.sub: 'Обучение игре в шахматы для самых маленьких. Игры учат детей внимательности, пониманию сравнительной силы фигур и важности проходных пешек. Работает на Android, iOS, Windows телефонах и компьютерах'
site.home.section2.main: 'Веб-Приложение Криббедж'
site.home.section2.sub: 'Криббадж игрок в веб-приложении. Используется алгоритм на основе ISMCTS для игры и перебор с весовыми таблицами для сброса. Тренируйся игре в 6-карточный Криббедж с оригинальным компьютерным оппонентом на телефоне, планшете или компьютере'
site.home.section3.main: 'Другие ссылки'
site.home.section3.sub: 'прошлые архивные ссылки'
button.learnmore: 'Узнать больше'
site.kidschess.title1: 'KidsChess от Клуба Рифата'
site.kidschess.subtitle1: 'Обучение игре в шахматы для самых маленьких'
site.links.title1: 'Ссылки на ресурсы'
site.links.subtitle1: 'архивные ссылки'
site.404.title1: 'Страница не найдена'
site.404.subtitle1: 'К сожалению запрашиваемая страница не найдена.'
pr20210331.title: 'Приложение KidsChess: Обучающие шахматные игры для детей.'
pr20210331.subtitle: 'Пресс-Релиз Март 31, 2021'
cookies.title: 'KidsChess Политика Cookies'
cookies.subtitle: 'мы не собираем персональные данные'
privacy.title: 'Политика конфиденциальности KidsChess'
privacy.subtitle: 'никакие личные данные не собираются и не используются'





