site.home.title: 'Web Applications to play and learn games: KidsChess, Cribbage'
site.home.h1: 'Gaming Web Apps'
site.home.h2: 'Play, learn, have fun'
site.home.section1.main: 'KidsChess: Chess games for children'
site.home.section1.sub: 'Learning to play chess for the little ones. Games teach children to pay attention, understand the relative strength of pieces and the importance of passed pawns. On Android, iOS, Windows phone and computers'
site.home.section2.main: 'Cribbage Web App'
site.home.section2.sub: 'Web-App Cribbage player. Uses ISMCTS-based algorithm to play and full search with weight tables to discard. Practice 6-card Cribbage with the original computer opponent on phones, tablets or computers'
site.home.section3.main: 'Other links'
site.home.section3.sub: 'recent archived links'
button.learnmore: 'Learn More'
site.kidschess.title1: 'KidsChess by Rifat Club'
site.kidschess.subtitle1: 'Learning to play chess for the little ones'
site.links.title1: 'Recent links'
site.links.subtitle1: 'links archive'
pr20210331.title: 'KidsChess: Teaching games for children in one App'
pr20210331.subtitle: 'Press Release Mar 2021'





