site.home.title: 'Aplicaciones web para jugar y aprender juegos: KidsChess, Cribbage'
site.home.h1: 'Aplicaciones web de juegos'
site.home.h2: 'Juega, aprende, diviértete'
site.home.section1.main: 'KidsChess: juegos de ajedrez para niños'
site.home.section1.sub: 'Aprender a jugar al ajedrez para los más pequeños. Los juegos enseñan a los niños a prestar atención, comprender la fuerza relativa de las piezas y la importancia de los peones pasados. En Android, iOS, teléfonos con Windows y computadoras'
site.home.section2.main: 'Aplicación web Cribbage'
site.home.section2.sub: 'Reproductor de Cribbage de aplicación web. Utiliza un algoritmo basado en ISMCTS para jugar y una búsqueda completa con tablas de peso para descartar. Practica Cribbage de 6 cartas con el oponente original de la computadora en teléfonos, tabletas o computadoras'
site.home.section3.main: 'Otros enlaces'
site.home.section3.sub: 'enlaces archivados recientes'
button.learnmore: 'Aprender más'
site.kidschess.title1: 'KidsChess de Rifat Club'
site.kidschess.subtitle1: 'Aprender a jugar al ajedrez para los más pequeños'
site.links.title1: 'Enlaces recientes'
site.links.subtitle1: 'archivo de enlaces'
site.404.title1: 'Página no encontrada'
site.404.subtitle1: 'Lo sentimos, pero la página solicitada no se encuentra.'
pr20210331.title: 'KidsChess: juegos de enseñanza para niños en una sola aplicación'
pr20210331.subtitle: 'Comunicado de prensa de marzo de 2021'
cookies.title: 'Política de cookies de KidsChess'
cookies.subtitle: 'no se recopilan datos personales'






